### PR TITLE
adding Next && Prev to entities that need them

### PR DESCRIPTION
**Pull request by tzapu**

### CODE REVIEW

**Comment by tzapu** [comment]
hey @corpetty , maybe you can chime in on this? any ideas on how to better do something similar?

**Comment by tzapu** [comment]
closing this as I am adding more features
feedback is still welcome  tho

**Comment by corpetty** [comment]
ah shit, I went on vacation and didn't see this.  I can reopen this if you want.

**Comment by corpetty** [comment]
I hadn't finsihed the whole API, I was then going to go back and clean up structure logic (including prev/next and pagination. )

**Comment by tzapu** [comment]
very cool, glad to have you back. 
no worries, i ll submit a new one with some more features tomorrow, but let me know if the Prev/Back make sense like that or you have another way of doing it. i don t like it completly, but I am also out of ideas :P

**Comment by corpetty** [comment]
sounds good.. I'll try and review this tomorrow as my plate is full tonight.

**Pull request closed without merging**
